media: "img"
content:
  - name: "main"
    label: "Главная"
    path: "index.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
  - name: "about"
    label: "О школе"
    path: "about.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
  - name: "directions"
    label: "Направления"
    path: "directions.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
  - name: "trainers"
    label: "Тренеры"
    path: "trainers.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
  - name: "schedule"
    label: "Расписание"
    path: "schedule.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
  - name: "prices"
    label: "Цены"
    path: "prices.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
  - name: "contacts"
    label: "Контакты"
    path: "contacts.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
  - name: "faq"
    label: "FAQ"
    path: "faq.html"
    type: "file"
    fields:
      - { name: "body", label: "Текст страницы", type: "body" }
