source: "."
output: "."
build:
  install_command: null
  build_command: null
editing:
  visual_editor:
    enabled: true
collections:
  pages:
    name: "Страницы"
    path: "/"
    output: true
    filter: "**/*.html"
optimization:
  images: false
