source: .
editor:
  default_path:
timezone: Etc/UTC
output: .
build:
  install_command:
  build_command:
editing:
  visual_editor:
    enabled: true
    open_links_in_new_window: false
  source_editor:
    enabled: true
collections:
  pages:
    name: Страницы
    path: /
    output: true
    filter: '**/*.html'
    exclude: '**/admin/**'
    _enabled_editors:
      - visual
      - content
automatic_editing:
  enabled: true
  default_attributes:
    data-cms-editable: true
