backend:
  name: github
  repo: safersss/wildcards-fencing
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - name: "index"
        label: "Главная"
        file: "index.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
      - name: "about"
        label: "О школе"
        file: "about.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
      - name: "directions"
        label: "Направления"
        file: "directions.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
      - name: "trainers"
        label: "Тренеры"
        file: "trainers.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
      - name: "schedule"
        label: "Расписание"
        file: "schedule.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
      - name: "prices"
        label: "Цены"
        file: "prices.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
      - name: "contacts"
        label: "Контакты"
        file: "contacts.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
      - name: "faq"
        label: "FAQ"
        file: "faq.html"
        fields:
          - { name: "body", label: "Содержание", widget: "markdown" }
